In [3]:
import numpy as np

In [4]:
mylist = [1,2,3,4]

In [5]:
np.array(mylist)

array([1, 2, 3, 4])

In [6]:
nested_list = [[1,2],[3,4],[5,6]]

In [7]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(2)

array([0.90898975, 0.29190068])

In [21]:
np.random.rand(3,4)

array([[0.28500919, 0.71818031, 0.79698297, 0.74205478],
       [0.14362631, 0.30572414, 0.65290238, 0.88370244],
       [0.10304271, 0.1323045 , 0.70116089, 0.13058581]])

In [24]:
np.random.randn(5,5)

array([[ 0.73306261,  0.02561667,  0.07770633, -1.72809943,  0.99354091],
       [ 0.92374669,  0.97283059, -0.38958575, -0.56217977, -0.13999423],
       [ 1.1379115 ,  0.73816117, -0.87268641,  0.96162067,  1.6797308 ],
       [ 0.77329618,  0.40020316,  1.39129325,  0.98372384, -0.26030035],
       [-0.03972486,  1.88947114,  1.33975116, -0.08305438,  1.42527469]])

In [25]:
np.random.randint(1,100,5)

array([94, 33, 83,  5, 89])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.shape

(25,)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [35]:
ranarr.max()

39

In [36]:
ranarr.argmax()

7

In [37]:
ranarr.min()

2

In [38]:
ranarr.argmin()

9

In [39]:
ranarr.dtype

dtype('int64')