In [1]:
import numpy as np

In [4]:
arr = np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5]

5

In [7]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[:5]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:]=100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])

In [25]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr2d[2]

array([35, 40, 45])

In [27]:
arr2d[0,1]

10

In [28]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [29]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr = np.arange(1,11)

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])